name: TinaCMS Build

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build TinaCMS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # HIER IST DIE Ã„NDERUNG: 'npm install' statt 'npm ci'
      # Das repariert den Fehler mit der package-lock.json
      - name: Install Dependencies
        run: npm install

      - name: Build TinaCMS
        env:
 # Client ID ist jetzt fest in config.js, wir brauchen hier nur noch das Token
          TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
        run: npm run build
